# This file was generated by GoReleaser. DO NOT EDIT.
cask "saw" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "6fb454f0d2691138d17ef90b532e86849065659732bad9a1931f6bd93dfa7252"
      url "https://github.com/apppackio/saw/releases/download/v#{version}/saw_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a705a41fad416fcc0176a5ddd864f0212fc4f026604ac2338171cd36deccff28"
      url "https://github.com/apppackio/saw/releases/download/v#{version}/saw_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4b477246569ac44cdc55db5eaa0a8b6743e33858896993b49679a95b1ef9f14d"
      url "https://github.com/apppackio/saw/releases/download/v#{version}/saw_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "75f50810573449b1c0f965bc112a3f87efe359156a0850aa33f42e28fd699470"
      url "https://github.com/apppackio/saw/releases/download/v#{version}/saw_#{version}_linux_amd64.tar.gz"
    end
  end

  name "saw"
  desc "Fast, multipurpose tool for AWS CloudWatch Logs"
  homepage "https://github.com/apppackio/saw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saw"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/saw"]
    end
  end

  # No zap stanza required
end
