# This file was generated by GoReleaser. DO NOT EDIT.
cask "saw" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "666eea4c1caf61b420aa02276902622840780270736723e836fbc09ae4240117"
      url "https://github.com/apppackio/saw/releases/download/v#{version}/saw_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9420742f1b95892331dfc7dcbd21787827446f22afd874100072562a34086374"
      url "https://github.com/apppackio/saw/releases/download/v#{version}/saw_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "23dd64aecff2dac5006d637406d22507165cab9f86bcdbea76a537944c54da87"
      url "https://github.com/apppackio/saw/releases/download/v#{version}/saw_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e86244545e389e3b7d00e96ed497ae869b1ac34753e319d1cb903f2b9670c535"
      url "https://github.com/apppackio/saw/releases/download/v#{version}/saw_#{version}_linux_amd64.tar.gz"
    end
  end

  name "saw"
  desc "Fast, multipurpose tool for AWS CloudWatch Logs"
  homepage "https://github.com/apppackio/saw"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "saw"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/saw"]
    end
  end

  # No zap stanza required
end
